In [1]:
# for importion numpy#
import numpy as np

In [8]:
# For Checking numpy version#
np.__version__

'1.26.4'

In [9]:
np.version.version

'1.26.4'

In [10]:
sales=[4321,4567,5678,9843]
profit=[232,987,965,456]

In [11]:
sales

[4321, 4567, 5678, 9843]

In [12]:
profit

[232, 987, 965, 456]

In [15]:
for i in range(0,len(sales)):
    print(sales[i]/profit[i])

18.625
4.627152988855117
5.883937823834197
21.585526315789473


In [ ]:
# Matrix is a collection of row and column, Its a 2 D array#

In [ ]:
#Tensors: collection of Matrix, Its a n Dimension array#

In [16]:
# How can we convert a list type to an array #
sales_array=np.array(sales)
profit_array=np.array(profit)

In [18]:
profit_array

array([232, 987, 965, 456])

In [19]:
sales_array

array([4321, 4567, 5678, 9843])

In [21]:
sales_array/profit_array

array([18.625     ,  4.62715299,  5.88393782, 21.58552632])

In [22]:
sales_us=[10,15,20,25]
sales_eu=[30,35,40,45]
sales_jp=[50,55,60,65]

In [24]:
# How can we convert 3 sales data into array #
sales_matrix=np.array([sales_us,sales_eu,sales_jp])

In [25]:
sales_matrix

array([[10, 15, 20, 25],
       [30, 35, 40, 45],
       [50, 55, 60, 65]])

In [29]:
# If I want to fetch 60 from the array #
sales_matrix[2,2]

60

In [46]:
sales_matrix[0:2,1:3]

array([[15, 20],
       [35, 40]])

In [47]:
# How to find mean from an array #
np.mean(sales_matrix)

37.5

In [48]:
# 0 is column wise#
#1 is row wise #
np.mean(sales_matrix,axis=0)

array([30., 35., 40., 45.])

In [50]:
np.shape(sales_matrix)

(3, 4)